<?PHP
	return [
		'slan' => 'ru_RU',
		'name' => 'Русский',
		[
			'title' => [
				'home' => 'Главная страница',
				'404' => 'Страница не найдена',
				'login' => 'Вход на сайт',
				'register' => 'Регистрация',
				'purchases' => 'Мои покупки',
				'contacts' => 'Контакты',
				'garants' => 'Гарантии',
				'reviews' => 'Отзывы',
				'wallet' => 'Кошелёк',
				'admin_main' => 'Основные настройки',
				'admin_users' => 'Пользователи',
				'admin_wallet' => 'Платёжные системы',
				'admin_product' => 'Управление товарами',
				'admin_dev' => 'Уголок разработчика',
				'admin_category' => 'Управление категориями',
				'profile' => '_LOGIN_'
			],
			'errors' => [
				'exploit' => 'Прямой вызов скрипта',
				'token' => 'Неверный токен',
				'access' => 'Недостаточно прав',
				'empty_data' => 'Заполните все данные!',
				'not_auth' => 'Вы не авторизованы',
				'no_text' => 'Вы ничего не написали',
				'no_product' => 'У вас нет этого товара',
				'no_page' => 'Запрашиваемая страница не найдена!',
				'template' => 'Не найден шаблон: _TEMPLATE_',
				'exists_user' => 'Запрашиваемый пользователь не найден!',
				'exists_login' => 'Имя пользователя уже занято',
				'login' => 'Неверный логин или пароль!',
				'success_login' => 'Успешная авторизация!',
				'success_register' => 'Успешная регистрация!',
				'search_product' => 'Запрашиваемый товар не найден!',
				'money' => 'Недостаточно средств!',
				'groups' => 'Нет групп',
				'category' => 'Нет категорий',
				'wallet' => 'Платёжная система отключена'
			],
			'noty' => [
				'update_cache' => 'Кэш обновлён',
				'clear_reviews' => 'Отзывы почищены',
				'clear_pays' => 'Покупки очищены',
				'save_data' => 'Данные сохранены',
				'success_operation'	=> 'Операция прошла успешно!',
				'add_content' => 'Контент добавлен',
				'end_reviews' => 'Спасибо за ваш отзыв!',
				'success' => 'Успех!',
				'no_operation' => 'Нет операций.',
				'no_reviews' => 'Отзывов нет.',
				'no_users' => 'Нет пользователей',
				'no_product' => 'Товаров нет',
				'no_purchases' => 'Вы ничего не купили.',
				'thank_you' => 'Спасибо вам!<br>Проверьте список своих покупок.'
			],
			'top_horizontal' => [
				'home' => 'Главная',
				'wallet' => 'Кошелёк',
				'purchases' => 'Покупки',
				'panel' => 'Админ панель'
			],
			'mini_menu' => [
				'main' => 'Главная страница',
				'vk' => 'Мы вконтакте',
				'wallet' => 'Кошелёк',
				'purchases' => 'Покупки',
				'worksma' => 'Торговая площадка'
			],
			'login' => [
				'title' => 'Вход на сайт',
				'username' => 'Логин',
				'password' => 'Пароль',
				'sumbit' => 'Войти',
				'to' => 'Войти через',
				'register' => 'Нет аккаунта?'
			],
			'register' => [
				'title' => 'Регистрация',
				'first_name' => 'Имя',
				'last_name' => 'Фамилия',
				'username' => 'Логин',
				'password' => 'Пароль',
				'login' => 'Уже есть аккаунт?',
				'sumbit' => 'Зарегистрироваться'
			],
			'wallet' => [
				'expenses' => 'Потрачено',
				'balance' => 'Текущий баланс'
			],
			'purchases' => [
				'title' => 'Покупки',
				'download' => 'Скачать',
				'delete' => 'Удалить'
			],
			'purse' => [
				'noty' => 'Пользователь _UID_ пополнил баланс на сумму _AMOUNT_ руб., через систему _SYSTEM_',
				'history' => 'Пополнение профиля',
				'sending' => 'Пополнение профиля: _LOGIN_'
			],
			'admin' => [
				'main_options_title' => 'Основные настройки',
				'main_options_name' => 'Название магазина',
				'main_options_description' => 'Описание магазина',
				'main_options_tags' => 'Ключевые слова',
				'main_options_template' => 'Стиль сайта',
				'main_options_cache' => 'Сбросить кэш',
				'main_options_reviews' => 'Очистить отзывы',
				'main_options_pays' => 'Очистить логи пополнений',
				'main_options_vk_title' => 'Приложение вконтакте',
				'main_options_vk_id' => 'ID приложения',
				'main_options_vk_key' => 'Защищённый ключ',
				'main_options_vk_service' => 'Сервисный ключ доступа',
				
				'product_add' => 'Добавление товара',
				'product_description' => 'Опишите свой товар и его возможности',
				'product_names' => 'Например: Скрипт магазина.',
				
				'wallet_title' => 'Платёжные системы',
				'wallet_lava_id' => 'ID магазина',
				'wallet_lava_secret' => 'Секретный ключ',
				'wallet_qiwi_secret' => 'Секретный ключ',
				'wallet_fk_id' => 'ID магазина',
				'wallet_fk_secret' => 'Секретный ключ 1',
				'wallet_fk_secret2' => 'Секретный ключ 2',
				
				'last_update' => 'Последнее обновление'
			],
			'navAdminLeftVertical' => [
				'title' => 'Навигация',
				'home' => 'Основные настройки',
				'dev' => 'Уголок разработчика',
				'users' => 'Пользователи',
				'wallet' => 'Платёжные системы',
				'product' => 'Управление товарами',
				'category' => 'Настройки каталогов'
			],
			'placeholder' => [
				'shopid' => 'ID магазина',
				'secret' => 'Секретный ключ...'
			],
			'other' => [
				'copyright' => 'Копирайт &copy; 2022. Все права сохранены.',
				'category' => 'Категория',
				'price' => 'Стоимость',
				'file' => 'Файл',
				'image_main' => 'Главная картинка',
				'screenshots' => 'Скриншоты',
				'primarily_auth' => '<a href="/login">Авторизуйтесь</a>, чтобы купить.',
				'login' => 'Войти на сайт',
				'logout' => 'Выйти',
				'revert' => 'Вернуться на сайт',
				'groups' => 'Группы',
				'add' => 'Добавить',
				'names' => 'Наименование',
				'description' => 'Описание',
				'update' => 'Обновить',
				'version' => 'Версия',
				'from' => 'От',
				'sales' => 'Продажи',
				'income' => 'Прибыль',
				'products' => 'Товары',
				'users' => 'Пользователи',
				'edit' => 'Изменить',
				'cancel' => 'Отмена',
				'enabled' => 'Включен',
				'disabled' => 'Выключен',
				'position' => 'Позиция',
				'access' => 'Права доступа',
				'balance' => 'Баланс',
				'free' => 'Бесплатно',
				'achievement' => 'Достижения'
			]
		]
	];